
server:
  port: 9001
spring:
  application:
    name: springsessiondemo
  redis:
    host: 192.168.188.128
    port: 6379
    password: root
  session:
    store-type: redis
    timeout: 1800  #??????????????